export const SCREEN_NAME: any = {
  HISTORY_TAB: "HISTORY_TAB",
  ADD_GAME_TAB: "ADD_GAME_TAB",
  LIST_USER_TAB: "LIST_USER_TAB",
  START_SCREEN: "START_SCREEN",
  HISTORY_SCREEN: "HISTORY_SCREEN",
  ADD_GAME_SCREEN: "ADD_GAME_SCREEN",
  LIST_USER_SCREEN: "LIST_USER_SCREEN",
}